### ISSUE TITLE
Missing Header and src files in your repos. Its not working

### ISSUE THREAD

**Issue by jeromemoses** [husarnet/husarnet-esp32-platformio#5]
![image](https://user-images.githubusercontent.com/109733726/235298855-6ca129a6-5421-43d6-aab3-a7b93aea269c.png)

Header is not available in your library, there is no header mentioned in platformio library. Also missing src files for your library which must contain .h .c files.

**Comment by pidpawel** [comment]
Hi! 
This is not how this integration works. This library is merely an example/tutorial how to use our **framework** (which is a fork of the mainline esp32 framework as of now), which in turn contains an actual library with the files you've mentioned.

If you want to use it, have a look at our tutorial https://husarnet.com/docs/tutorial-esp32-platformio/

Feel free to reopen the issue if you need any further assistance

--
Have a wonderful day
pidpawel
